services:

    etcd1:
        image: pgha-etcd-3.5
        restart: unless-stopped
        environment:
          ENDPOINTS: etcd1:2380,etcd2:2380,etcd3:2380,etcd4:2380,etcd5:2380
        command:
            - '/usr/bin/etcd'
            - '--name=etcd1'
            - '--initial-advertise-peer-urls=http://etcd1:2380'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2379'
            - '--advertise-client-urls=http://etcd1:2379'
            - '--heartbeat-interval=250'
            - '--election-timeout=1250'
            - '--initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380,etcd5=http://etcd5:2380'
            - '--initial-cluster-state=new'
            - '--initial-cluster-token=pgha'
        networks:
          net1:
            priority: 1000
          net2:
            priority: 10
        ports:
            - 2379
        volumes:
            - etcd1:/etcd_data
        hostname: etcd1
        container_name: pgha-etcd1 



    etcd2:
        image: pgha-etcd-3.5
        restart: unless-stopped
        environment:
          ENDPOINTS: etcd1:2380,etcd2:2380,etcd3:2380,etcd4:2380,etcd5:2380
        command:
            - '/usr/bin/etcd'
            - '--name=etcd2'
            - '--initial-advertise-peer-urls=http://etcd2:2380'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2379'
            - '--advertise-client-urls=http://etcd2:2379'
            - '--heartbeat-interval=250'
            - '--election-timeout=1250'
            - '--initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380,etcd5=http://etcd5:2380'
            - '--initial-cluster-state=new'
            - '--initial-cluster-token=pgha'
        networks:
          net1:
            priority: 1000
          net2:
            priority: 10
        ports:
            - 2379
        volumes:
            - etcd2:/etcd_data
        hostname: etcd2
        container_name: pgha-etcd2 



    etcd3:
        image: pgha-etcd-3.5
        restart: unless-stopped
        environment:
          ENDPOINTS: etcd1:2380,etcd2:2380,etcd3:2380,etcd4:2380,etcd5:2380
        command:
            - '/usr/bin/etcd'
            - '--name=etcd3'
            - '--initial-advertise-peer-urls=http://etcd3:2380'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2379'
            - '--advertise-client-urls=http://etcd3:2379'
            - '--heartbeat-interval=250'
            - '--election-timeout=1250'
            - '--initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380,etcd5=http://etcd5:2380'
            - '--initial-cluster-state=new'
            - '--initial-cluster-token=pgha'
        networks:
          net1:
            priority: 1000
          net2:
            priority: 10
        ports:
            - 2379
        volumes:
            - etcd3:/etcd_data
        hostname: etcd3
        container_name: pgha-etcd3 



    etcd4:
        image: pgha-etcd-3.5
        restart: unless-stopped
        environment:
          ENDPOINTS: etcd1:2380,etcd2:2380,etcd3:2380,etcd4:2380,etcd5:2380
        command:
            - '/usr/bin/etcd'
            - '--name=etcd4'
            - '--initial-advertise-peer-urls=http://etcd4:2380'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2379'
            - '--advertise-client-urls=http://etcd4:2379'
            - '--heartbeat-interval=250'
            - '--election-timeout=1250'
            - '--initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380,etcd5=http://etcd5:2380'
            - '--initial-cluster-state=new'
            - '--initial-cluster-token=pgha'
        networks:
          net1:
            priority: 1000
          net2:
            priority: 10
        ports:
            - 2379
        volumes:
            - etcd4:/etcd_data
        hostname: etcd4
        container_name: pgha-etcd4 



    etcd5:
        image: pgha-etcd-3.5
        restart: unless-stopped
        environment:
          ENDPOINTS: etcd1:2380,etcd2:2380,etcd3:2380,etcd4:2380,etcd5:2380
        command:
            - '/usr/bin/etcd'
            - '--name=etcd5'
            - '--initial-advertise-peer-urls=http://etcd5:2380'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2379'
            - '--advertise-client-urls=http://etcd5:2379'
            - '--heartbeat-interval=250'
            - '--election-timeout=1250'
            - '--initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380,etcd5=http://etcd5:2380'
            - '--initial-cluster-state=new'
            - '--initial-cluster-token=pgha'
        networks:
          net1:
            priority: 1000
          net2:
            priority: 10
        ports:
            - 2379
        volumes:
            - etcd5:/etcd_data
        hostname: etcd5
        container_name: pgha-etcd5 




    pg1-node1:
        depends_on: 
          - etcd1
          - etcd2
          - etcd3
          - etcd4
          - etcd5
        environment:
          ETCD_NODES: etcd1:2379,etcd2:2379,etcd3:2379,etcd4:2379,etcd5:2379
          NODE_NAME: pg1-node1
          CFG_DIR: /pgha/config
          PATRONI_CFG: /pgha/config/patroni.conf
          DATADIR: /pgdata/16
          PG_BIN_DIR: /usr/lib/postgresql/16/bin
          NAMESPACE: pgha
          SCOPE: pgha_cluster
          STANZA_NAME: pgha_db
          PGBACKREST_SERVER: pgbackrest

        image: pgha-pg16-patroni
        restart: unless-stopped
        cap_add:
          - SYS_ADMIN
        entrypoint: /entrypoint.sh
        networks:
          net1:
            priority: 1000
          net2:
            priority: 10
          net3:
            priority: 10
        ports:
          - 50551:5432
        volumes:
          - pg1-node1-data:/pgdata
          - pg1-node1-home:/var/lib/postgresql
          - pg1-node1-conf:/pgha/config
        hostname: pg1-node1
        container_name: pgha-pg1-node1




    pg1-node2:
        depends_on: 
          - etcd1
          - etcd2
          - etcd3
          - etcd4
          - etcd5
        environment:
          ETCD_NODES: etcd1:2379,etcd2:2379,etcd3:2379,etcd4:2379,etcd5:2379
          NODE_NAME: pg1-node2
          CFG_DIR: /pgha/config
          PATRONI_CFG: /pgha/config/patroni.conf
          DATADIR: /pgdata/16
          PG_BIN_DIR: /usr/lib/postgresql/16/bin
          NAMESPACE: pgha
          SCOPE: pgha_cluster
          STANZA_NAME: pgha_db
          PGBACKREST_SERVER: pgbackrest

        image: pgha-pg16-patroni
        restart: unless-stopped
        cap_add:
          - SYS_ADMIN
        entrypoint: /entrypoint.sh
        networks:
          net1:
            priority: 1000
          net2:
            priority: 10
          net3:
            priority: 10
        ports:
          - 50552:5432
        volumes:
          - pg1-node2-data:/pgdata
          - pg1-node2-home:/var/lib/postgresql
          - pg1-node2-conf:/pgha/config
        hostname: pg1-node2
        container_name: pgha-pg1-node2




    pg2-node1:
        depends_on: 
          - etcd1
          - etcd2
          - etcd3
          - etcd4
          - etcd5
        environment:
          ETCD_NODES: etcd1:2379,etcd2:2379,etcd3:2379,etcd4:2379,etcd5:2379
          NODE_NAME: pg2-node1
          CFG_DIR: /pgha/config
          PATRONI_CFG: /pgha/config/patroni.conf
          DATADIR: /pgdata/16
          PG_BIN_DIR: /usr/lib/postgresql/16/bin
          NAMESPACE: pgha
          SCOPE: pgha_cluster
          STANZA_NAME: pgha_db
          PGBACKREST_SERVER: pgbackrest

        image: pgha-pg16-patroni
        restart: unless-stopped
        cap_add:
          - SYS_ADMIN
        entrypoint: /entrypoint.sh
        networks:
          net1:
            priority: 10
          net2:
            priority: 1000
          net3:
            priority: 10
        ports:
          - 50553:5432
        volumes:
          - pg2-node1-data:/pgdata
          - pg2-node1-home:/var/lib/postgresql
          - pg2-node1-conf:/pgha/config
        hostname: pg2-node1
        container_name: pgha-pg2-node1




    pg2-node2:
        depends_on: 
          - etcd1
          - etcd2
          - etcd3
          - etcd4
          - etcd5
        environment:
          ETCD_NODES: etcd1:2379,etcd2:2379,etcd3:2379,etcd4:2379,etcd5:2379
          NODE_NAME: pg2-node2
          CFG_DIR: /pgha/config
          PATRONI_CFG: /pgha/config/patroni.conf
          DATADIR: /pgdata/16
          PG_BIN_DIR: /usr/lib/postgresql/16/bin
          NAMESPACE: pgha
          SCOPE: pgha_cluster
          STANZA_NAME: pgha_db
          PGBACKREST_SERVER: pgbackrest

        image: pgha-pg16-patroni
        restart: unless-stopped
        cap_add:
          - SYS_ADMIN
        entrypoint: /entrypoint.sh
        networks:
          net1:
            priority: 10
          net2:
            priority: 1000
          net3:
            priority: 10
        ports:
          - 50554:5432
        volumes:
          - pg2-node2-data:/pgdata
          - pg2-node2-home:/var/lib/postgresql
          - pg2-node2-conf:/pgha/config
        hostname: pg2-node2
        container_name: pgha-pg2-node2




    pg3-node1:
        depends_on: 
          - etcd1
          - etcd2
          - etcd3
          - etcd4
          - etcd5
        environment:
          ETCD_NODES: etcd1:2379,etcd2:2379,etcd3:2379,etcd4:2379,etcd5:2379
          NODE_NAME: pg3-node1
          CFG_DIR: /pgha/config
          PATRONI_CFG: /pgha/config/patroni.conf
          DATADIR: /pgdata/16
          PG_BIN_DIR: /usr/lib/postgresql/16/bin
          NAMESPACE: pgha
          SCOPE: pgha_cluster
          STANZA_NAME: pgha_db
          PGBACKREST_SERVER: pgbackrest

        image: pgha-pg16-patroni
        restart: unless-stopped
        cap_add:
          - SYS_ADMIN
        entrypoint: /entrypoint.sh
        networks:
          net1:
            priority: 10
          net2:
            priority: 10
          net3:
            priority: 1000
        ports:
          - 50555:5432
        volumes:
          - pg3-node1-data:/pgdata
          - pg3-node1-home:/var/lib/postgresql
          - pg3-node1-conf:/pgha/config
        hostname: pg3-node1
        container_name: pgha-pg3-node1




    pg3-node2:
        depends_on: 
          - etcd1
          - etcd2
          - etcd3
          - etcd4
          - etcd5
        environment:
          ETCD_NODES: etcd1:2379,etcd2:2379,etcd3:2379,etcd4:2379,etcd5:2379
          NODE_NAME: pg3-node2
          CFG_DIR: /pgha/config
          PATRONI_CFG: /pgha/config/patroni.conf
          DATADIR: /pgdata/16
          PG_BIN_DIR: /usr/lib/postgresql/16/bin
          NAMESPACE: pgha
          SCOPE: pgha_cluster
          STANZA_NAME: pgha_db
          PGBACKREST_SERVER: pgbackrest

        image: pgha-pg16-patroni
        restart: unless-stopped
        cap_add:
          - SYS_ADMIN
        entrypoint: /entrypoint.sh
        networks:
          net1:
            priority: 10
          net2:
            priority: 10
          net3:
            priority: 1000
        ports:
          - 50556:5432
        volumes:
          - pg3-node2-data:/pgdata
          - pg3-node2-home:/var/lib/postgresql
          - pg3-node2-conf:/pgha/config
        hostname: pg3-node2
        container_name: pgha-pg3-node2



    pgbackrest:
        environment: 
          NODE1: pg1-node1
          NODE2: pg1-node2
          NODE3: pg2-node1
          NODE4: pg2-node2
          NODE5: pg3-node1
          NODE6: pg3-node2
          CFG_DIR: /pgha/config
          REPO_PATH: /pgha/pgbackrest
          DATADIR: /pgdata
          STANZA_NAME: pgha_db
          PGPORT: 5432

        image: pgha-pgbackrest
        restart: unless-stopped
        networks:
          net1:
            priority: 1000
          net2:
            priority: 10
          net3:
            priority: 10
        volumes:
          - pgbackrest-data:/pgha/pgbackrest
          - pgbackrest-home:/var/lib/postgresql
        hostname: pgbackrest
        container_name: pgha-pgbackrest
        cap_add:
          - SYS_ADMIN
        entrypoint: /entrypoint.sh


volumes: 
    etcd1:
    etcd2:
    etcd3:
    etcd4:
    etcd5: 
    pg1-node1-data:
    pg1-node1-home:
    pg1-node1-conf:
    pg1-node2-data:
    pg1-node2-home:
    pg1-node2-conf:
    pg2-node1-data:
    pg2-node1-home:
    pg2-node1-conf:
    pg2-node2-data:
    pg2-node2-home:
    pg2-node2-conf:
    pg3-node1-data:
    pg3-node1-home:
    pg3-node1-conf:
    pg3-node2-data:
    pg3-node2-home:
    pg3-node2-conf:
    pg4-node1-data:
    pg4-node1-home:
    pg4-node1-conf:
    pg4-node2-data:
    pg4-node2-home:
    pg4-node2-conf:
    pg5-node1-data:
    pg5-node1-home:
    pg5-node1-conf:
    pg5-node2-data:
    pg5-node2-home:
    pg5-node2-conf:
    pg6-node1-data:
    pg6-node1-home:
    pg6-node1-conf:
    pg6-node2-data:
    pg6-node2-home:
    pg6-node2-conf: 
    pgbackrest-data:
    pgbackrest-home: 

networks:
    net1:
    net2:
    net3:

